fix: Remove broken ExtentReportManager listener from TestNG XML files
ROOT CAUSE:
TestNG error: 'Couldn't find a constructor in class ExtentReportManager'

The TestNG XML files had:
  <listener class-name='com.egalvanic.utils.ExtentReportManager'/>

But ExtentReportManager:
1. Has a PRIVATE constructor (cannot be instantiated)
2. Does NOT implement ITestListener or ISuiteListener
3. Is a UTILITY class with only STATIC methods

TestNG requires listeners to have:
- A public no-argument constructor
- Implement ITestListener, ISuiteListener, etc.

FIX:
Removed the <listeners> section from all 7 TestNG XML files:
- testng-auth.xml
- testng-site.xml
- testng-phase1.xml
- testng-phase2.xml
- testng-phase3.xml
- testng-phase4.xml
- testng-phase5.xml

ExtentReportManager is ALREADY called from BaseTest via:
- @BeforeSuite: ExtentReportManager.initReports()
- @AfterMethod: ExtentReportManager.logFail/logPass/logSkip
- @AfterSuite: ExtentReportManager.flushReports()

The listener declaration was REDUNDANT and BROKEN.

Also removed parallel='false' which was causing warning:
'parallel' value 'false' is no longer valid, defaulting to 'none'